services:
    # backend:
    #     build: .
    #     container_name: nightjetenjoyers_backend
    #     restart: always
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - postgres
    # environment:

    postgres:
        image: postgres
        container_name: nightjetenjoyers_database
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_DB: "schaepplidb"
            POSTGRES_USER: "schaeppli"
            POSTGRES_PASSWORD: tiajeiY6saeX9faaleexe0eeQuitahl4UShie5Aiqua4ahgei1eitiNgiejai7TohlaWa1baime
        ports:
            - "5432:5432"
        expose:
            - 5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    auth:
        image: quay.io/keycloak/keycloak
        container_name: nightjetenjoyers_auth
        ports:
            - "8080:8080"
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/schaepplidb
            KC_DB_USERNAME: schaeppli
            KC_DB_PASSWORD: tiajeiY6saeX9faaleexe0eeQuitahl4UShie5Aiqua4ahgei1eitiNgiejai7TohlaWa1baime
            KC_HOSTNAME: localhost
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command:
            - start-dev
            - --import-realm
        volumes:
            - ./data/keycloak/realm.json:/opt/keycloak/data/import/realm.json
